version: "3.9"

services:
  web_app:
    build: .
    image: web_app
    depends_on:
      - db
    ports:
      - "9800:9800"
    #    command:
    #      - python3 start.py
    env_file:
      - .env
    volumes:
      - .:/opt/app

  db:
    image: postgres:14.1
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  postgres_data:
    name: postgres_data

networks:
  default:
    external:
      name: tst_kfk