version: "3.9"

services:
  web_app:
    build:
      context: .
    image: web_app
    depends_on:
      - db
    ports:
      - "9800:9800"
    #    command:
    #      - python3 start.py
    env_file:
      - .env
    volumes:
      - .:/opt/app

  web_app_tests:
    build:
      context: .
      dockerfile: tests/Dockerfile
    depends_on:
      - web_app
      - db
    env_file:
      - .env
    volumes:
      - .:/opt/app

  db:
    image: postgres:14.1
    ports:
      - "5432:5432"
    env_file:
      - .env
